version: "3.8"

services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/usr/app

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
